* Past
** FOSDEM 2017 (Feb 5, 2017 @ 14:30)
Janneke's first talk about Gnu Mes and his plans for MesCC
https://video.fosdem.org/2017/K.4.601/guixsdbootstrap.vp8.webm
https://archive.fosdem.org/2017/schedule/event/guixsdbootstrap/attachments/slides/1693/export/events/attachments/guixsdbootstrap/slides/1693/mes_fosdem.pdf
(a copy are in fosdem_2017 folder)
(He didn't know about stage0 yet, only saw the hex0 on guix's IRC channel)

** GHM 2017
Ricardo's first bootstrapping talk, presenting his bootstrapping work on Java
and presenting on the behalf of Jeremiah and Janneke for the work they have been
doing.
https://audio-video.gnu.org/video/ghm2017/2017-08--wurmus--reproducible-bootstrapping--ghm.webm
https://audio-video.gnu.org/video/ghm2017/2017-08--wurmus--reproducible-bootstrapping--ghm.pdf
(a copy are in ghm-2017 folder)
(He had a crash course on stage0 and Mes just 2 days before the talk)

** The Long Con 2018 (Nov 26, 2018 @ 10:00)
Mark's first talk about bootstrappability and elections
https://www.youtube.com/watch?v=tAFMFjc6mJk
(a copy are in longcon_2018 folder)

** FOSDEM 2019 (Feb 2, 2019 @ 15:20)
A beautiful talk by janneke about havling the size of the Guix bootstrap seed to 120MB.
https://video.fosdem.org/2019/K.4.201/gnumes.webm
https://archive.fosdem.org/2019/schedule/event/gnumes/attachments/slides/2848/export/events/attachments/gnumes/slides/2848/gnu_mes_fosdem19_v2.pdf
(a copy are in fosdem_2019 folder)

** Breaking Bitcoin 2019 (June 8, 2019 @ 15:00)
A brief talk by Carl Dong about bitcoin builds and the importance of bootstrappability
https://www.youtube.com/watch?v=I2iShmUTEl8

** Deb Conf 19 (July 23, 2019 @ 13:30)
Giovanni's first talk about his asmc and nbs; with his famous bootstrapping
evolution perspective.
https://meetings-archive.debian.net/pub/debian-meetings/2019/DebConf19/bootstrappable-debian-bof.webm
https://salsa.debian.org/gio/debconf2019_bootstrappable_debian
(a copy are in debconf_2019 folder)

** FOSDEM 2020 (Feb 2, 2020 @ 11:50am)
A brief talk by janneke about halving the size of the Guix bootstrap seed again, to 60MB.
https://video.fosdem.org/2020/AW1.125/gnumes.webm
https://fosdem.org/2020/schedule/event/gnumes/attachments/slides/3942/export/events/attachments/gnumes/slides/3942/fosdem20.pdf

** PackagingCon 2021
Civodul's guix talk on the packaging grail:
https://www.youtube.com/watch?v=tcTOkXlE_ac
And bootstrap bit starting at 5:20 to 8:44

And Jeremiah's first talk about his stage0 project.
https://www.youtube.com/watch?v=BpRef4U-4sI
From 8:52 to 10:48

** FOSDEM 2022 (Feb 6, 2022 @ 10:45)
A brief talk by ekaitz on his work on RISC-V bootstrapping
https://fosdem.org/2022/schedule/event/riscvadventures/

Video:
https://video.fosdem.org/2022/D.minimalistic/riscvadventures.webm

Slides:
https://fosdem.org/2022/schedule/event/riscvadventures/attachments/slides/4815/export/events/attachments/riscvadventures/slides/4815/Slides.pdf

** LAS 2023 (Apr 23, 2023, 10:00am)
A 40minute talk on the new bootstrapped root for the Freedesktop SDK

Video:
https://www.youtube.com/watch?v=jwMEDI4WsAE

** FOSDEM 2023 (Feb 4, 2023 @ noon)
A brief talk by ekaitz on his work on RISC-V bootstrapping
https://archive.fosdem.org/2023/schedule/event/guixriscv/

Video:
https://video.fosdem.org/2023/D.minimalistic/guixriscv.webm

Slides:
https://archive.fosdem.org/2023/schedule/event/guixriscv/attachments/slides/5325/export/events/attachments/guixriscv/slides/5325/RISCV_Bootstrap_guix.pdf

* Future
** FOSDEM 2024 (Feb 4, 2024 @11:20am)
A brief talk by ekaitz on his work on RISC-V bootstrapping
https://fosdem.org/2024/schedule/event/fosdem-2024-1755-risc-v-bootstrapping-in-guix-and-live-bootstrap/
